export * from "./__generated__/CharacterDetailCardFragment.graphql";
export * from "./__generated__/CharacterQuery.graphql";
export * from "./__generated__/CharactersCardFragment.graphql";
export * from "./__generated__/CharactersQuery.graphql";
export * from "./__generated__/EpisodeDetailCardFragment.graphql";
export * from "./__generated__/EpisodeQuery.graphql";
export * from "./__generated__/EpisodesListItemFragment.graphql";
export * from "./__generated__/EpisodesQuery.graphql";
export * from "./__generated__/LocationsQuery.graphql";
